import type {
  Artifact,
  ScenarioActionType,
  SettleStrategyType
} from "../../../../packages/contracts/types/runner.ts";

export type {
  Artifact,
  CategoryFilterSignalObservation,
  AgentAllowedNavigation,
  AgentCallbackEventType,
  AgentEvent,
  AgentEventBatch,
  AgentArtifactPolicy,
  AgentBudget,
  AgentDecisionSource,
  AgentEventType,
  AgentExecuteMessage,
  AgentFinalOutcome,
  AgentGoalType,
  AgentObservation,
  AgentObservationBudget,
  AgentObservationCandidateSummary,
  AgentObservationFormControlSummary,
  AgentObservationPageSignals,
  AgentOutcome,
  AgentOutcomeCategory,
  AgentOutcomeReasonCode,
  AgentOutcomeStatus,
  AgentPolicyDecision,
  AgentPolicyResult,
  AgentProductSelectionPolicy,
  AgentReplayHints,
  AgentReplayHintStep,
  AgentRiskClass,
  AgentRiskPolicy,
  AgentTask,
  AgentTestData,
  AgentTrace,
  AgentTraceCallbackPayload,
  AgentTraceRequest,
  AgentTurnTrace,
  ArtifactBatch,
  AxTreeObservation,
  AxTreeSummary,
  AccordionStateObservation,
  BrowserAccordionState,
  BrowserBackLinkCandidateSignal,
  BrowserCheckoutContext,
  BrowserFinalSubmitRelation,
  BrowserFormGroupRequiredState,
  BrowserKeyboardFocusState,
  BrowserPerformanceSummary,
  BrowserLoadingState,
  BrowserRepeatedGenericLinkGroup,
  BrowserStepIndicatorSignal,
  Checkpoint,
  CheckoutContextObservation,
  DiscoveryEntrypointCandidate,
  DiscoveryEntrypointType,
  DiscoveryCheckpoint,
  DiscoveryExecuteMessage,
  DiscoveryAcceptedPayload,
  DiscoveryCheckpointRequest,
  DiscoveryFinishedPayload,
  DiscoveryFailedPayload,
  DiscoverySummaryPayload,
  DiscoveryExecutePayload,
  DiscoveryEvidenceSignal,
  DiscoveryEvidenceSummary,
  DiscoveryFlowCandidate,
  DiscoveryFlowType,
  DiscoveryRecommendationLevel,
  DiscoveryObservation,
  DiscoveryObservationData,
  DiscoveryScenarioRecommendation,
  DiscoveryShallowNavigationVerification,
  DepthFromDiscoveryObservation,
  GoalActionCandidateObservation,
  GoalActionResultObservation,
  DomVisibilitySummary,
  InteractiveComponentBounds,
  InteractiveComponentLayout,
  InteractiveComponentObservationItem,
  InteractiveComponentVisibility,
  InteractiveComponentsObservation,
  JourneyActionRawObservation,
  KeyboardFocusStateObservation,
  LayoutVisibilitySummary,
  LayoutCollectorObservation,
  LoadingStateObservation,
  NetworkTimelineEvent,
  NetworkTimelineObservation,
  PathNavigationObservation,
  PageReadyTimingObservation,
  PerformanceMetricObservation,
  ProductDetailSignalObservation,
  ProductCardObservation,
  RunArtifactPolicy,
  RunExecuteMessage,
  RunnerAcceptedPayload,
  RunnerCheckpointsRequest,
  RunnerControlStatePayload,
  RunnerActionKind,
  RunnerExpectedOutcomeHint,
  RunnerFailedPayload,
  RunnerFinishedPayload,
  ScenarioAuthoringCandidate,
  ScenarioAuthoringAcceptedPayload,
  ScenarioAuthoringExecuteMessage,
  ScenarioAuthoringExecutePayload,
  ScenarioAuthoringFailedPayload,
  ScenarioAuthoringFinishedPayload,
  ScenarioAuthoringFailure,
  ScenarioAuthoringInput,
  ScenarioAuthoringJob,
  ScenarioAuthoringProviderPolicy,
  ScenarioAuthoringProviderTraceEntry,
  ScenarioAuthoringProviderType,
  ScenarioAuthoringProvenance,
  ScenarioAuthoringSelectedRecommendation,
  ScenarioAuthoringStatus,
  ScenarioAuthoringValidation,
  ScenarioAuthoringValidationIssue,
  ScenarioAction,
  ScenarioActionType,
  ScenarioPlan,
  ScenarioStage,
  ScenarioStep,
  SettleStrategy,
  SettleStrategyType,
  SiteDiscoveryResult,
  StepEvent,
  StepEventBatch,
  TargetDescriptor,
  TargetDescriptorMap,
  TextBlockMetricsObservation,
  VisibleTextBlockObservationItem
} from "../../../../packages/contracts/types/runner.ts";

export interface ArtifactDraft {
  artifactId: string;
  artifactType: Artifact["artifactType"];
  stepKey: string;
  mimeType: string;
  fileExtension: string;
  content: string;
  contentEncoding?: "utf8" | "base64";
  width?: number;
  height?: number;
}

export const scenarioActionTypes = [
  "goto",
  "click",
  "fill",
  "select",
  "scroll",
  "hover",
  "wait_for",
  "checkpoint",
  "stop_when"
] as const satisfies readonly ScenarioActionType[];

export const settleStrategyTypes = [
  "network_idle",
  "locator_visible",
  "response",
  "url_change",
  "spinner_hidden",
  "item_count_change",
  "fixed_short",
  "none"
] as const satisfies readonly SettleStrategyType[];
