import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('app routes /runs/:runId/report to the run report page before monitor matching', () => {
  const source = fs.readFileSync(new URL('../../src/app/App.tsx', import.meta.url), 'utf8');
  const appRoute = fs.readFileSync(new URL('../../src/app/appRoute.ts', import.meta.url), 'utf8');
  const pages = fs.readFileSync(new URL('../../src/pages/index.ts', import.meta.url), 'utf8');

  assert.match(source, /import \{ resolveAppRoute, resolveProtectedRouteGate/);
  assert.match(source, /<RunReportPage runId=\{route\.runId\} \/>/);
  assert.match(appRoute, /const reportRunId = getRunReportIdFromPath\(pathname\);[\s\S]*const runId = getRunIdFromPath\(pathname\);/);
  assert.match(pages, /runReport/);
  assert.match(pages, /:runId\/report/);
});

test('run report page follows the report.html result-first layout', () => {
  const page = fs.readFileSync(new URL('../../src/pages/run-report/RunReportPage.tsx', import.meta.url), 'utf8');
  const viewer = fs.readFileSync(new URL('../../src/features/report-viewer/components/RunReportViewer.tsx', import.meta.url), 'utf8');
  const state = fs.readFileSync(new URL('../../src/pages/run-report/lib/runReportState.ts', import.meta.url), 'utf8');
  const source = `${page}\n${viewer}\n${state}`;
  const mock = fs.readFileSync(new URL('../../src/features/report-viewer/lib/runReportMock.ts', import.meta.url), 'utf8');
  const viewModel = fs.readFileSync(new URL('../../src/features/report-viewer/lib/runReportViewModel.ts', import.meta.url), 'utf8');

  assert.match(source, /CTA 전환 마찰 분석/);
  assert.match(source, /function RunReportStatePage/);
  assert.match(source, /리포트 준비 중/);
  assert.match(source, /run-report-state-card__header/);
  assert.doesNotMatch(source, /getReportStateStatusLabel/);
  assert.match(source, />리포트<\/span>/);
  assert.match(source, /run-report-state-card__meta/);
  assert.doesNotMatch(source, /새 분석 만들기/);
  assert.match(source, /function RunReportLoadingShell/);
  assert.match(source, /if \(reportState\.kind === 'loading'\) \{[\s\S]*?<RunReportLoadingShell runId=\{runId\} title=\{reportState\.title\} \/>/);
  assert.match(source, /run-report-page run-report-page--loading/);
  assert.match(source, /run-report-hero-stats run-report-hero-stats--skeleton" aria-hidden="true"/);
  assert.match(source, /getRun\(runId\)/);
  assert.match(source, /getRunReport\(runId\)/);
  assert.match(source, /getReport\(reportProjection\.reportId\)/);
  assert.match(source, /generateRunReport\(runId\)/);
  assert.match(source, /requestRunAnalysis\(runId\)/);
  assert.match(source, /getRunEvidencePacket\(runId\)/);
  assert.match(source, /listRunArtifacts\(runId\)/);
  assert.match(source, /hydrateEvidenceArtifacts/);
  assert.match(source, /selectLatestScreenshotPreviewUrl/);
  assert.match(source, /fetchRunReportPreviewUrl/);
  assert.match(source, /void fetchRunReportPreviewUrl\(runId\)[\s\S]*if \(isActive\) \{[\s\S]*setReportPreviewUrl\(previewUrl\)/);
  assert.match(source, /\[isMockRun, reportProjection\?\.reportId, reportProjection\?\.reportStatus, reportProjection\?\.updatedAt, runId\]/);
  assert.match(source, /Artifact list is a preview\/download enhancement/);
  assert.match(source, /buildMockRunReportData/);
  assert.match(source, /buildRunReportFromApi/);
  assert.match(source, /buildRunReportFromEvidence/);
  assert.match(source, /reportProjection\?\.reportStatus === 'READY'/);
  assert.match(source, /\[evidencePacket, isMockRun, reportDetail, reportLoadError, reportPreviewUrl, reportProjection, run, runId, scenarioId, targetUrl\]/);
  assert.match(source, /sourceNotice: reportLoadError/);
  assert.match(source, /fallbackPreviewUrl: reportPreviewUrl/);
  assert.match(source, /useAuthenticatedResourceUrl\(selectedEvidencePreviewUrl\)/);
  assert.match(source, /const isEvidencePreviewResolving = Boolean\(selectedEvidencePreviewUrl && !evidencePreviewUrl\)/);
  assert.match(source, /useRef<HTMLDivElement \| null>\(null\)/);
  assert.match(source, /ref=\{evidencePreviewRef\}/);
  assert.match(source, /preview\.scrollTo\(\{ top: targetScrollTop, behavior: 'smooth' \}\)/);
  assert.match(source, /run-report-evidence-preview__canvas/);
  assert.match(source, /run-report-evidence-preview--resolving/);
  assert.match(source, /activeFinding\?\.highlight && !isEvidencePreviewResolving/);
  assert.match(source, /role="status"/);
  assert.match(source, /if \(isMockRun\)/);
  assert.match(source, /리포트 준비 중입니다/);
  assert.match(source, /리포트 생성/);
  assert.match(source, /분석 시작/);
  assert.match(source, /리포트 데이터 연결 대기 중입니다/);
  assert.match(source, /리포트 근거를 불러오는 중입니다/);
  assert.match(source, /실행 결과를 찾을 수 없습니다/);
  assert.match(source, /분석 완료/);
  assert.doesNotMatch(viewer, /Report ID:/);
  assert.match(source, /run-report-hero__meta/);
  assert.match(source, /run-report-hero-context/);
  assert.doesNotMatch(viewer, /\{report\.reportId\}/);
  assert.match(source, /RUNS_PATH/);
  assert.match(source, /실행 목록/);
  assert.match(source, /내보내기 · 준비 중/);
  assert.doesNotMatch(viewer, /Share Report/);
  assert.match(source, /isMockRunId\(runId\)/);
  assert.match(source, /aria-label="분석 화면 미리보기"/);
  assert.match(source, /총 단계/);
  assert.match(source, /마찰 지점/);
  assert.match(source, /소요 시간/);
  assert.match(source, /run-report-insight-summary/);
  assert.match(source, /우선 고칠 항목부터 확인하세요/);
  assert.match(source, /우선 개선 제안/);
  assert.match(source, /왜 필요한가요\?/);
  assert.match(source, /수정 후 확인할 것/);
  assert.match(source, /전환 흐름 진단/);
  assert.match(source, /run-report-decision-node__rail/);
  assert.doesNotMatch(source, /resolveDecisionNodeId/);
  assert.doesNotMatch(source, /resolveFindingIdForDecisionNode/);
  assert.doesNotMatch(source, /run-report-decision-node--active/);
  assert.doesNotMatch(source, /마찰 감지/);
  assert.doesNotMatch(source, /흐름 유지/);
  assert.doesNotMatch(source, /run-report-decision-node__tags/);
  assert.match(source, /관련 마찰 근거/);
  assert.match(source, /다음 개선 제안/);
  assert.match(source, /분석 화면/);
  assert.match(source, /분석 화면[\s\S]*우선 개선 제안[\s\S]*왜 필요한가요/);
  assert.match(source, /selectedRecommendationId/);
  assert.match(source, /setSelectedRecommendationId\(recommendation\.id\)/);
  assert.match(source, /selectedFindingId/);
  assert.match(source, /setSelectedFindingId\(finding\.id\)/);
  assert.match(source, /activeFinding\?\.previewImageUrl \?\? report\.evidencePreviewUrl/);
  assert.match(source, /evidencePreviewUrl \? ' run-report-evidence-preview--image' : ''/);
  assert.match(source, /나머지 \$\{hiddenFindingCount\}개 더보기/);
  assert.match(source, /전체 문제 접기/);
  assert.match(source, /aria-expanded=\{isFullFindingListOpen\}/);
  assert.match(source, /aria-pressed=\{activeFindingId === finding\.id\}/);
  assert.match(source, /주요 마찰 근거가 없습니다/);
  assert.match(source, /구간/);
  assert.match(source, /resolveLinkedFindingId/);
  assert.match(source, /resolveActiveFinding/);
  assert.match(source, /기대 효과/);
  assert.match(source, /적용 난이도/);
  assert.match(source, /관련 단계/);
  assert.match(source, /판단 신뢰도/);
  assert.match(source, /현재 우선 수정할 항목은 없습니다/);
  assert.match(source, /run-report-visual-panel/);
  assert.match(source, /run-report-insight-panel/);
  assert.match(source, /run-report-section--top-findings/);
  assert.match(source, /run-report-primary-nudge/);
  assert.match(source, /onMouseEnter=\{\(\) => setHoveredFindingId\(selectedRecommendationFindingId\)\}/);
  assert.match(source, /run-report-reason-card/);
  assert.match(source, /onMouseEnter=\{\(\) => setHoveredFindingId\(selectedRecommendationFinding\.id\)\}/);
  assert.match(source, /run-report-validation-check/);
  assert.match(source, /run-report-top-finding-list/);
  assert.match(source, /run-report-finding-full-list/);
  assert.match(source, /run-report-finding-row/);
  assert.match(source, /run-report-section--priority/);
  assert.match(source, /run-report-decision-map/);
  assert.match(source, /run-report-evidence-preview/);
  assert.doesNotMatch(source, /run-report-side-column/);
  assert.match(mock, /reportId/);
  assert.match(mock, /mock-report-evidence\.png/);
  assert.doesNotMatch(mock, /interface RunReportViewModel/);
  assert.match(viewModel, /interface RunReportViewModel/);
  assert.match(mock, /totalSteps/);
  assert.match(mock, /durationLabel/);
  assert.match(mock, /decisionNodes/);
  assert.match(mock, /사용자가 CTA를 발견했는가/);
  assert.match(mock, /CTA가 첫 화면에서 충분히 두드러지지 않음/);
  assert.match(mock, /issueId/);
  assert.match(mock, /priorityScore/);
  assert.match(mock, /evidenceRefs/);
  assert.match(mock, /previewImageUrl/);
  assert.match(mock, /expectedImpact/);
  assert.match(mock, /validationQuestion/);
  assert.match(mock, /rationale/);
  assert.match(mock, /CTA 직전 신뢰 요소 배치/);
  assert.match(mock, /입력 단계 진입 전 기대 정보가 부족함/);
});

test('run report css keeps result-first content in the live simulation cockpit tone', () => {
  const css = fs.readFileSync(new URL('../../src/features/report-viewer/styles/run-report-viewer.css', import.meta.url), 'utf8');

  assert.match(css, /\.run-report-page\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-grid-bg\s*\{[\s\S]*?radial-gradient\(#f1f5f9 1px/);
  assert.match(css, /\.run-report-brand\s*\{[\s\S]*?color: #7dd3fc/);
  assert.match(css, /\.run-report-topbar__export\s*\{[\s\S]*?background: #334155/);
  assert.doesNotMatch(css, /topbar__share/);
  assert.match(css, /\.run-report-topbar__link--secondary\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-topbar__link--secondary\s*\{[\s\S]*?text-transform: none/);
  assert.match(css, /\.run-report-topbar__link--secondary:hover\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-report-shell\s*\{[\s\S]*?height: calc\(100vh - 4rem\)/);
  assert.match(css, /\.run-report-hero\s*\{[\s\S]*?align-items: center/);
  assert.match(css, /\.run-report-hero__meta\s*\{[\s\S]*?display: flex/);
  assert.match(css, /\.run-report-hero-context\s*\{[\s\S]*?display: grid/);
  assert.match(css, /\.run-report-hero-context div\s*\{[\s\S]*?gap: 0\.22rem/);
  assert.match(css, /\.run-report-hero h1\s*\{[\s\S]*?font-size: clamp\(1\.14rem, 2vw, 1\.45rem\)/);
  assert.match(css, /\.run-report-hero \.run-report-hero__notice\s*\{[\s\S]*?background: rgba\(254, 252, 232, 0\.92\)/);
  assert.match(css, /\.run-report-hero-stats\s*\{[\s\S]*?background: #fff/);
  assert.doesNotMatch(css.match(/\.run-report-hero-stats\s*\{[^}]*\}/)?.[0] ?? '', /box-shadow/);
  assert.match(css, /\.run-report-hero-stats:hover\s*\{[\s\S]*?border-color: rgba\(14, 165, 233, 0\.5\)/);
  assert.doesNotMatch(css, /\.run-report-hero-stats div:hover/);
  assert.match(css, /\.run-report-hero-stats div \+ div::before\s*\{[\s\S]*?background: #e2e8f0/);
  assert.match(css, /\.run-report-layout\s*\{[\s\S]*?width: 100%/);
  assert.match(css, /\.run-report-layout\s*\{[\s\S]*?grid-template-columns: minmax\(0, 1fr\) minmax\(32rem, 36rem\)/);
  assert.match(css, /\.run-report-layout\s*\{[\s\S]*?padding: 1\.5rem 1\.75rem 1\.75rem/);
  assert.match(css, /\.run-report-visual-panel\s*\{[\s\S]*?height: 100%/);
  assert.match(css, /\.run-report-visual-panel\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-visual-panel\s*\{[\s\S]*?overflow: hidden/);
  assert.match(css, /@media \(max-width: 1080px\)[\s\S]*?\.run-report-visual-panel\s*\{[\s\S]*?height: min\(42rem, calc\(100svh - 8rem\)\)/);
  assert.match(css, /\.run-report-evidence-card\s*\{[\s\S]*?height: 100%/);
  assert.match(css, /\.run-report-evidence-card\s*\{[\s\S]*?grid-template-rows: minmax\(0, 1fr\)/);
  assert.match(css, /\.run-report-browser\s*\{[\s\S]*?border: 1px solid #e5e7eb/);
  assert.match(css, /\.run-report-browser__bar\s*\{[\s\S]*?height: 2\.35rem/);
  assert.match(css, /\.run-report-browser__address\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-browser__mode-pill\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-report-browser__mode-pill\s*\{[\s\S]*?color: #64748b/);
  assert.match(css, /\.run-report-insight-panel\s*\{[\s\S]*?border: 1px solid #e5e7eb/);
  assert.match(css, /\.run-report-insight-panel\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-insight-panel\s*\{[\s\S]*?box-shadow: 0 18px 46px rgba\(148, 163, 184, 0\.12\)/);
  assert.match(css, /\.run-report-insight-summary\s*\{[\s\S]*?position: sticky/);
  assert.match(css, /\.run-report-insight-summary h2\s*\{[\s\S]*?font-size: 1rem/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section\s*\{[\s\S]*?scroll-margin-top: 3\.7rem/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section \+ \.run-report-section\s*\{[\s\S]*?box-shadow: inset 0 1px 0 var\(--run-report-line-soft\)/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section--top-findings\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section--priority\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-section-heading h2\s*\{[\s\S]*?font-size: 0\.82rem/);
  assert.doesNotMatch(css, /\.run-report-insight-nav/);
  assert.doesNotMatch(css, /\.run-report-section-heading span/);
  assert.doesNotMatch(css, /\.run-report-section-heading--plain/);
  assert.doesNotMatch(css, /\.run-report-nudge-card__/);
  assert.doesNotMatch(css, /!important/);
  assert.match(css, /\.run-report-primary-nudge\s*\{[\s\S]*?border-left: 4px solid #0ea5e9/);
  assert.match(css, /\.run-report-primary-nudge__meta\s*\{[\s\S]*?grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.run-report-next-nudges button\s*\{[\s\S]*?grid-template-columns: auto minmax\(0, 1fr\) auto/);
  assert.match(css, /\.run-report-reason-card\s*\{[\s\S]*?border-left: 3px solid #cbd5e1/);
  assert.match(css, /\.run-report-reason-card--high\s*\{[\s\S]*?border-left-color: #ef4444/);
  assert.match(css, /\.run-report-validation-check\s*\{[\s\S]*?background: #f8fdff/);
  assert.match(css, /\.run-report-top-finding-list\s*\{[\s\S]*?grid-template-columns: 1fr/);
  assert.doesNotMatch(css, /\.run-report-top-finding-card__button\s*\{[\s\S]*?min-height: 15rem/);
  assert.match(css, /\.run-report-top-finding-card__button\s*\{[\s\S]*?border-left: 3px solid #cbd5e1/);
  assert.match(css, /\.run-report-top-finding-card--high \.run-report-top-finding-card__button\s*\{[\s\S]*?border-left-color: #ef4444/);
  assert.match(css, /\.run-report-top-finding-card dl\s*\{[\s\S]*?display: flex/);
  assert.doesNotMatch(css.match(/\.run-report-top-finding-empty\s*\{[^}]*\}/)?.[0] ?? '', /border-left/);
  assert.match(css, /\.run-report-top-finding-empty,\s*\n\.run-report-reason-empty,\s*\n\.run-report-nudge-empty\s*\{[\s\S]*?background: #f8fafc/);
  assert.doesNotMatch(css, /\.run-report-top-finding-empty::before/);
  assert.match(css, /\.run-report-top-finding-card__button\[aria-pressed="true"\]\s*\{[\s\S]*?border-color: #0ea5e9/);
  assert.match(css, /\.run-report-finding-more > button\s*\{[\s\S]*?background: #f0f9ff/);
  assert.match(css, /\.run-report-finding-row\s*\{[\s\S]*?grid-template-columns: 3rem minmax\(0, 1fr\) max-content/);
  assert.doesNotMatch(css.match(/\.run-report-nudge-empty\s*\{[^}]*\}/)?.[0] ?? '', /border-left/);
  assert.doesNotMatch(css.match(/\.run-report-reason-empty\s*\{[^}]*\}/)?.[0] ?? '', /border-left/);
  assert.doesNotMatch(css, /\.run-report-nudge-empty::before/);
  assert.doesNotMatch(css, /\.run-report-reason-empty::before/);
  assert.doesNotMatch(css, /\.run-report-decision-map::before/);
  assert.doesNotMatch(css, /\.run-report-decision-node::after/);
  assert.match(css, /\.run-report-decision-node__rail\s*\{[\s\S]*?left: 0\.98rem/);
  assert.match(css, /\.run-report-decision-node__rail-base\s*\{[\s\S]*?background: #e2e8f0/);
  assert.match(css, /\.run-report-decision-node__rail-signal\s*\{[\s\S]*?linear-gradient/);
  assert.doesNotMatch(css, /\.run-report-decision-node--active/);
  assert.doesNotMatch(css.match(/\.run-report-decision-node__body\s*\{[^}]*\}/)?.[0] ?? '', /border/);
  assert.doesNotMatch(css.match(/\.run-report-decision-node__body\s*\{[^}]*\}/)?.[0] ?? '', /background/);
  assert.match(css, /\.run-report-decision-node--friction \.run-report-decision-node__badge\s*\{[\s\S]*?background: #fef2f2/);
  assert.doesNotMatch(css, /\.run-report-decision-node--friction \.run-report-decision-node__body/);
  assert.doesNotMatch(css, /\.run-report-decision-node__head/);
  assert.doesNotMatch(css, /\.run-report-decision-node__tags/);
  assert.match(css, /\.run-report-decision-node p\s*\{[\s\S]*?color: #64748b/);
  assert.match(css, /\.run-report-evidence-preview\s*\{[\s\S]*?flex: 1[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-evidence-preview--image\s*\{[\s\S]*?overflow-y: auto/);
  assert.match(css, /\.run-report-evidence-preview__canvas\s*\{[\s\S]*?position: relative/);
  assert.match(css, /\.run-report-friction-marker\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-report-friction-marker::before\s*\{[\s\S]*?border-radius: 999px/);
  assert.match(css, /\.run-report-friction-marker::before\s*\{[\s\S]*?rgba\(245, 158, 11, 0\.72\)/);
  assert.match(css, /\.run-report-friction-marker span\s*\{[\s\S]*?background: #78350f/);
  assert.doesNotMatch(css.match(/\.run-report-friction-marker\s*\{[^}]*\}/)?.[0] ?? '', /#0ea5e9/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.run-report-browser__mode-pill\s*\{[\s\S]*?display: none/);
  assert.match(css, /\.run-report-evidence-preview__image\s*\{[\s\S]*?height: auto/);
  assert.match(css, /\.run-report-evidence-preview__site\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-evidence-preview--resolving\s*\{[\s\S]*?background: linear-gradient/);
  assert.match(css, /\.run-report-evidence-preview__hero button\s*\{[\s\S]*?background: #111827/);
  assert.match(css, /\.run-report-topbar__link\s*\{[\s\S]*?background: #334155/);
  assert.match(css, /\.run-report-state-card a,\s*\n\.run-report-state-card button\s*\{[\s\S]*?background: #334155/);
  assert.match(css, /\.run-report-state-card__header\s*\{[\s\S]*?margin-bottom: 1rem/);
  assert.doesNotMatch(css, /\.run-report-state-card::before/);
  assert.doesNotMatch(css, /\.run-report-state-card > span/);
  assert.match(css, /\.run-report-state-card__actions a\s*\{[\s\S]*?background: rgba\(240, 249, 255, 0\.88\)/);
  assert.match(css, /\.run-report-state-card__meta\s*\{[\s\S]*?border-top: 1px solid #f1f5f9/);
  assert.match(css, /\.run-report-loading-status\s*\{[\s\S]*?background: rgba\(240, 249, 255, 0\.78\)/);
  assert.match(css, /\.run-report-skeleton-line\s*\{[\s\S]*?border-radius: 999px/);
  assert.match(css, /@keyframes runReportSkeletonPulse/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
  assert.doesNotMatch(css, /run-report-side-column/);
  assert.match(css, /@media \(max-width: 1080px\)/);
  assert.match(css, /@media \(max-width: 760px\)/);
});

test('authenticated resource hook avoids raw api image urls and cleans blob urls', () => {
  const source = fs.readFileSync(
    new URL('../../src/shared/lib/authenticatedResourceUrl.ts', import.meta.url),
    'utf8',
  );

  assert.match(source, /useState<string \\| null>\(null\)/);
  assert.doesNotMatch(source, /useState<string \\| null>\(resourceUrl \?\? null\)/);
  assert.match(source, /URL\.createObjectURL\(blob\)/);
  assert.match(source, /URL\.revokeObjectURL\(objectUrl\)/);
  assert.match(source, /\.catch\(\(\) => \{[\s\S]*?setResolvedUrl\(null\)/);
});

test('run monitor exposes a report CTA into /runs/:runId/report', () => {
  const source = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.tsx', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.css', import.meta.url), 'utf8');

  assert.match(source, /import \{ handleSpaNavigationClick, replaceAppPath \}/);
  assert.match(source, /import \{ buildRunReportPath \}/);
  assert.match(source, /const reportCtaState = resolveRunMonitorReportCtaState/);
  assert.match(source, /const reportPath = reportCtaState\.canOpenReport[\s\S]*buildRunReportPath\(run\.id/);
  assert.match(source, /getRunReport\(run\.id\)/);
  assert.match(source, /generateRunReport\(requestedRunId\)/);
  assert.match(source, /requestRunAnalysis\(requestedRunId\)/);
  assert.match(source, /reportCtaState\.titleLabel/);
  assert.match(source, /reportCtaState\.kind !== 'hidden'/);
  assert.match(source, /분석 결과 리포트/);
  assert.match(source, /handleSpaNavigationClick\(event, reportPath\)/);
  assert.match(source, /<a href=\{reportPath\} onClick=\{openReport\}>\{reportCtaActionLabel\}<\/a>/);
  assert.match(source, /리포트 생성/);
  assert.match(source, /분석 시작/);
  assert.doesNotMatch(source, /모의 리포트 보기/);
  assert.match(css, /\.run-monitor-report-cta\s*\{[\s\S]*?background: rgba\(240, 249, 255, 0\.58\)/);
  assert.match(css, /\.run-monitor-report-cta__actions a,\s*\n\.run-monitor-report-cta__actions button\s*\{[\s\S]*?background: #475569/);
  assert.match(css, /\.run-monitor-report-cta__actions a,\s*\n\.run-monitor-report-cta__actions button\s*\{[\s\S]*?width: 100%/);
  assert.match(css, /\.run-monitor-report-cta__actions button:disabled\s*\{[\s\S]*?cursor: not-allowed/);
});
