import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('app routes /runs/:runId/report to the run report page before monitor matching', () => {
  const source = fs.readFileSync(new URL('../../src/app/App.tsx', import.meta.url), 'utf8');
  const appRoute = fs.readFileSync(new URL('../../src/app/appRoute.ts', import.meta.url), 'utf8');
  const pages = fs.readFileSync(new URL('../../src/pages/index.ts', import.meta.url), 'utf8');

  assert.match(source, /import \{ resolveAppRoute, resolveProtectedRouteGate/);
  assert.match(source, /<RunReportPage runId=\{route\.runId\} \/>/);
  assert.match(appRoute, /const reportRunId = getRunReportIdFromPath\(pathname\);[\s\S]*const runId = getRunIdFromPath\(pathname\);/);
  assert.match(pages, /runReport/);
  assert.match(pages, /:runId\/report/);
});

test('run report page follows the report.html result-first layout', () => {
  const page = fs.readFileSync(new URL('../../src/pages/run-report/RunReportPage.tsx', import.meta.url), 'utf8');
  const viewer = fs.readFileSync(new URL('../../src/features/report-viewer/components/RunReportViewer.tsx', import.meta.url), 'utf8');
  const state = fs.readFileSync(new URL('../../src/pages/run-report/lib/runReportState.ts', import.meta.url), 'utf8');
  const source = `${page}\n${viewer}\n${state}`;
  const mock = fs.readFileSync(new URL('../../src/features/report-viewer/lib/runReportMock.ts', import.meta.url), 'utf8');
  const viewModel = fs.readFileSync(new URL('../../src/features/report-viewer/lib/runReportViewModel.ts', import.meta.url), 'utf8');
  const loadingShell = page.match(/function RunReportLoadingShell[\s\S]*?\n}\n\nexport function RunReportPage/)?.[0] ?? '';

  assert.match(source, /전환 흐름 리포트/);
  assert.doesNotMatch(source, /CTA 전환 마찰 분석/);
  assert.match(source, /function RunReportStatePage/);
  assert.match(source, /리포트 준비 중/);
  assert.match(source, /run-report-state-card__header/);
  assert.doesNotMatch(source, /getReportStateStatusLabel/);
  assert.match(source, /완료된 리포트/);
  assert.match(source, /run-report-state-card__meta/);
  assert.doesNotMatch(source, /새 분석 만들기/);
  assert.match(source, /function RunReportLoadingShell/);
  assert.match(source, /if \(reportState\.kind === 'loading'\) \{[\s\S]*?<RunReportLoadingShell title=\{reportState\.title\} \/>/);
  assert.match(source, /run-report-page run-report-page--loading/);
  assert.match(loadingShell, /run-report-sr-only/);
  assert.doesNotMatch(loadingShell, /run-report-grid-bg|run-report-topbar|run-report-shell|run-report-hero|분석 화면|JudgeResult/);
  assert.match(source, /getRun\(runId\)/);
  assert.match(source, /getRunReport\(runId\)/);
  assert.match(source, /getReport\(reportProjection\.reportId\)/);
  assert.match(source, /generateRunReport\(runId\)/);
  assert.match(source, /requestRunAnalysis\(runId\)/);
  assert.match(source, /getRunEvidencePacket\(runId\)/);
  assert.match(source, /listRunArtifacts\(runId\)/);
  assert.match(source, /hydrateEvidenceArtifacts/);
  assert.match(source, /selectLatestScreenshotPreviewUrl/);
  assert.match(source, /fetchRunReportPreviewUrl/);
  assert.match(source, /void fetchRunReportPreviewUrl\(runId\)[\s\S]*if \(isActive\) \{[\s\S]*setReportPreviewUrl\(previewUrl\)/);
  assert.match(source, /\[isMockRun, reportProjection\?\.reportId, reportProjection\?\.reportStatus, reportProjection\?\.updatedAt, runId\]/);
  assert.match(source, /Artifact list is a preview\/download enhancement/);
  assert.match(source, /buildMockRunReportData/);
  assert.match(source, /buildRunReportFromApi/);
  assert.match(source, /buildRunReportFromEvidence/);
  assert.match(source, /reportProjection\?\.reportStatus === 'READY'/);
  assert.match(source, /\[evidencePacket, isMockRun, reportDetail, reportLoadError, reportPreviewUrl, reportProjection, run, runId, scenarioId, targetUrl\]/);
  assert.match(source, /sourceNotice: reportLoadError/);
  assert.match(source, /fallbackPreviewUrl: reportPreviewUrl/);
  assert.match(source, /useAuthenticatedResourceUrl\(selectedEvidencePreviewUrl\)/);
  assert.match(viewer, /formatDisplayUrl/);
  assert.match(viewer, /const targetUrlLabel = formatDisplayUrl\(report\.targetUrl\)/);
  assert.match(viewer, /<dd title=\{report\.targetUrl\}>\{targetUrlLabel\}<\/dd>/);
  assert.match(source, /const isEvidencePreviewResolving = Boolean\(selectedEvidencePreviewUrl && !evidencePreviewUrl\)/);
  assert.match(source, /useRef<HTMLDivElement \| null>\(null\)/);
  assert.match(source, /ref=\{evidencePreviewRef\}/);
  assert.match(source, /preview\.scrollTo\(\{ top: targetScrollTop, behavior: 'smooth' \}\)/);
  assert.match(source, /run-report-evidence-preview__canvas/);
  assert.match(source, /run-report-evidence-preview--resolving/);
  assert.match(source, /frictionMarkers/);
  assert.match(source, /role="status"/);
  assert.match(source, /if \(isMockRun\)/);
  assert.match(source, /리포트 준비 중입니다/);
  assert.match(source, /리포트 생성/);
  assert.match(source, /분석 시작/);
  assert.match(source, /리포트 데이터 연결 대기 중입니다/);
  assert.match(source, /리포트 근거를 불러오는 중입니다/);
  assert.match(source, /실행 결과를 찾을 수 없습니다/);
  assert.match(source, /완료된 리포트/);
  assert.doesNotMatch(viewer, />분석 완료<\/span>/);
  assert.doesNotMatch(viewer, /Report ID:/);
  assert.match(source, /run-report-hero__meta/);
  assert.match(source, /run-report-hero-context/);
  assert.doesNotMatch(viewer, /\{report\.reportId\}/);
  assert.match(source, /RUNS_PATH/);
  assert.match(source, /실행 목록/);
  assert.match(source, /리포트 다운로드/);
  assert.match(source, /createRunReportExport/);
  assert.match(source, /downloadReportExport/);
  assert.match(source, /REPORT_EXPORT_PENDING_MESSAGE/);
  assert.doesNotMatch(viewer, /Share Report/);
  assert.match(source, /isMockRunId\(runId\)/);
  assert.match(source, /aria-label="분석 화면 미리보기"/);
  assert.match(source, /총 단계/);
  assert.match(source, /마찰 지점/);
  assert.match(source, /소요 시간/);
  assert.match(source, /run-report-insight-summary/);
  assert.match(source, /run-report-insight-summary__label/);
  assert.match(source, /먼저 고칠 항목/);
  assert.match(source, /개선 후보/);
  assert.match(source, /전환 흐름/);
  assert.match(source, /개선 후보를 선택하면 진단과 관련 근거가 함께 바뀝니다/);
  assert.match(source, /selectedRecommendationId/);
  assert.match(source, /selectRecommendation\(recommendation\)/);
  assert.match(source, /selectedFindingId/);
  assert.match(source, /setSelectedFindingId\(findingId\)/);
  assert.match(source, /activeFinding\?\.previewImageUrl \?\? report\.evidencePreviewUrl/);
  assert.match(source, /function previewUrlForFinding\(finding: ReportFinding, fallbackUrl: string \| null \| undefined\)/);
  assert.match(source, /recommendation\.findingId && !map\.has\(recommendation\.findingId\)/);
  assert.match(source, /previewUrlForFinding\(finding, report\.evidencePreviewUrl\) === selectedEvidencePreviewUrl/);
  assert.match(source, /evidencePreviewUrl \? ' run-report-evidence-preview--image' : ''/);
  assert.match(source, /TOP_RECOMMENDATION_COUNT/);
  assert.match(source, /topRecommendations/);
  assert.match(source, /전체 후보 \{recommendations\.length\}개 보기/);
  assert.match(source, /isAllRecommendationsOpen/);
  assert.match(source, /aria-expanded=\{isAllRecommendationsOpen\}/);
  assert.match(source, /tabIndex=\{isAllRecommendationsOpen \? 0 : -1\}/);
  assert.match(source, /run-report-recommendation-tab/);
  assert.match(source, /run-report-all-recommendations__panel/);
  assert.match(source, /run-report-selected-action/);
  assert.match(source, /run-report-stage-group/);
  assert.match(source, /run-report-stage-chips/);
  assert.match(source, /REPORT_FLOW_STAGES/);
  assert.match(source, /resolveActiveFlowStageId/);
  assert.match(source, /reportFlowStageLabel/);
  assert.match(source, /const flowNodes = REPORT_FLOW_STAGES/);
  assert.match(source, /첫 화면/);
  assert.match(source, /가치 판단/);
  assert.match(source, /행동 선택/);
  assert.match(source, /run-report-stage-chip--active/);
  assert.match(source, /aria-current=\{isActive \? 'step' : undefined\}/);
  assert.match(source, /문제 요약/);
  assert.match(source, /개선 방향/);
  assert.match(source, /판단 근거/);
  assert.doesNotMatch(source, /확인할 신호/);
  assert.doesNotMatch(source, /화면 위치/);
  assert.doesNotMatch(source, /전환이 끊기는 지점입니다/);
  assert.match(source, /resolveLinkedFindingId/);
  assert.match(source, /resolveActiveFinding/);
  assert.match(source, /현재 우선 수정할 항목은 없습니다/);
  assert.match(source, /run-report-visual-panel/);
  assert.match(source, /run-report-insight-panel/);
  assert.match(source, /run-report-section--priority/);
  assert.match(source, /run-report-evidence-preview/);
  assert.doesNotMatch(source, /run-report-side-column/);
  assert.doesNotMatch(source, /run-report-action-card/);
  assert.doesNotMatch(source, /run-report-stage-strip/);
  assert.match(mock, /reportId/);
  assert.match(mock, /mock-report-evidence\.png/);
  assert.doesNotMatch(mock, /interface RunReportViewModel/);
  assert.match(viewModel, /interface RunReportViewModel/);
  assert.match(mock, /totalSteps/);
  assert.match(mock, /durationLabel/);
  assert.match(mock, /decisionNodes/);
  assert.match(mock, /사용자가 CTA를 발견했는가/);
  assert.match(mock, /CTA가 첫 화면에서 충분히 두드러지지 않음/);
  assert.match(mock, /issueId/);
  assert.match(mock, /priorityScore/);
  assert.match(mock, /evidenceRefs/);
  assert.match(mock, /previewImageUrl/);
  assert.match(mock, /expectedImpact/);
  assert.match(mock, /validationQuestion/);
  assert.match(mock, /rationale/);
  assert.match(mock, /CTA 직전 신뢰 요소 배치/);
  assert.match(mock, /입력 단계 진입 전 기대 정보가 부족함/);
});

test('run report css keeps result-first content in the live simulation cockpit tone', () => {
  const css = fs.readFileSync(new URL('../../src/features/report-viewer/styles/run-report-viewer.css', import.meta.url), 'utf8');
  const viewer = fs.readFileSync(new URL('../../src/features/report-viewer/components/RunReportViewer.tsx', import.meta.url), 'utf8');

  assert.match(css, /\.run-report-page\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-page--loading\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-grid-bg\s*\{[\s\S]*?radial-gradient\(#f1f5f9 1px/);
  assert.match(css, /\.run-report-brand\s*\{[\s\S]*?color: #7dd3fc/);
  assert.match(css, /\.run-report-topbar\s*\{[\s\S]*?border-bottom: 1px solid rgba\(248, 250, 252, 1\)/);
  assert.doesNotMatch(css.match(/\.run-report-topbar\s*\{[^}]*\}/)?.[0] ?? '', /box-shadow/);
  assert.match(css, /\.run-report-topbar__right\s*\{[\s\S]*?gap: 0\.65rem/);
  assert.match(css, /\.run-report-topbar__export\s*\{[\s\S]*?background: #334155/);
  assert.match(css, /\.run-report-topbar__export\s*\{[\s\S]*?height: 2\.05rem/);
  assert.match(css, /\.run-report-topbar__export\s*\{[\s\S]*?padding: 0 0\.86rem/);
  assert.match(css, /\.run-report-export-status\s*\{[\s\S]*?font-size: 0\.78rem/);
  assert.doesNotMatch(css, /topbar__share/);
  assert.match(css, /\.run-report-topbar__link--secondary\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-topbar__link--secondary\s*\{[\s\S]*?text-transform: none/);
  assert.match(css, /\.run-report-topbar__link--secondary:hover\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-report-shell\s*\{[\s\S]*?height: calc\(100vh - 4rem\)/);
  assert.match(css, /\.run-report-hero\s*\{[\s\S]*?align-items: center/);
  assert.match(css, /\.run-report-hero\s*\{[\s\S]*?min-height: 3\.4rem/);
  assert.match(css, /\.run-report-hero\s*\{[\s\S]*?border-bottom: 1px solid #f1f5f9/);
  assert.match(css, /\.run-report-hero\s*\{[\s\S]*?padding: 0\.68rem 2rem/);
  assert.doesNotMatch(css.match(/\.run-report-hero\s*\{[^}]*\}/)?.[0] ?? '', /box-shadow/);
  assert.match(css, /\.run-report-hero__copy\s*\{[\s\S]*?display: flex/);
  assert.match(css, /\.run-report-hero__copy\s*\{[\s\S]*?align-items: center/);
  assert.match(css, /\.run-report-hero__meta\s*\{[\s\S]*?display: flex/);
  assert.match(css, /\.run-report-hero-context\s*\{[\s\S]*?display: flex/);
  assert.match(css, /\.run-report-hero-context\s*\{[\s\S]*?gap: 0\.78rem/);
  assert.match(css, /\.run-report-hero-context div\s*\{[\s\S]*?gap: 0\.34rem/);
  assert.match(css, /\.run-report-hero-context div \+ div::before\s*\{[\s\S]*?height: 0\.9rem/);
  assert.match(css, /\.run-report-tag\s*\{[\s\S]*?font-size: 0\.56rem/);
  assert.match(css, /\.run-report-tag\s*\{[\s\S]*?line-height: 1\.1/);
  assert.match(css, /\.run-report-hero h1\s*\{[\s\S]*?font-size: 0\.82rem/);
  assert.match(css, /\.run-report-hero h1\s*\{[\s\S]*?font-weight: 850/);
  assert.match(css, /\.run-report-hero-context dt\s*\{[\s\S]*?font-size: 0\.56rem/);
  assert.match(css, /\.run-report-hero-context dt\s*\{[\s\S]*?color: #94a3b8/);
  assert.match(css, /\.run-report-hero-context dd\s*\{[\s\S]*?display: block/);
  assert.match(css, /\.run-report-hero-context dd\s*\{[\s\S]*?font-size: 0\.82rem/);
  assert.match(css, /\.run-report-hero \.run-report-hero__notice\s*\{[\s\S]*?flex-basis: 100%/);
  assert.match(css, /\.run-report-hero \.run-report-hero__notice\s*\{[\s\S]*?background: rgba\(254, 252, 232, 0\.92\)/);
  assert.match(css, /\.run-report-hero-stats\s*\{[\s\S]*?display: flex/);
  assert.match(css, /\.run-report-hero-stats\s*\{[\s\S]*?gap: 0\.78rem/);
  assert.match(css, /\.run-report-hero-stats\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-hero-stats\s*\{[\s\S]*?border: 0/);
  assert.doesNotMatch(css.match(/\.run-report-hero-stats\s*\{[^}]*\}/)?.[0] ?? '', /box-shadow/);
  assert.doesNotMatch(css, /\.run-report-hero-stats:hover/);
  assert.doesNotMatch(css, /\.run-report-hero-stats div:hover/);
  assert.match(css, /\.run-report-hero-stats div\s*\{[\s\S]*?display: flex/);
  assert.match(css, /\.run-report-hero-stats div\s*\{[\s\S]*?align-items: baseline/);
  assert.match(css, /\.run-report-hero-stats dt\s*\{[\s\S]*?font-size: 0\.56rem/);
  assert.match(css, /\.run-report-hero-stats dt\s*\{[\s\S]*?color: #94a3b8/);
  assert.match(css, /\.run-report-hero-stats dd\s*\{[\s\S]*?font-size: 1rem/);
  assert.match(css, /\.run-report-hero-stats dd\s*\{[\s\S]*?font-weight: 900/);
  assert.match(css, /\.run-report-hero-stats dd\.run-report-hero-stats__danger\s*\{[\s\S]*?color: #0ea5e9/);
  assert.match(css, /\.run-report-hero-stats div \+ div::before\s*\{[\s\S]*?height: 0\.9rem/);
  assert.match(css, /\.run-report-hero-stats div \+ div::before\s*\{[\s\S]*?background: #e5e7eb/);
  assert.match(css, /\.run-report-layout\s*\{[\s\S]*?width: 100%/);
  assert.match(css, /\.run-report-layout\s*\{[\s\S]*?grid-template-columns: minmax\(0, 1fr\) minmax\(32rem, 36rem\)/);
  assert.match(css, /\.run-report-layout\s*\{[\s\S]*?padding: 1\.5rem 1\.75rem 1\.75rem/);
  assert.match(css, /\.run-report-visual-panel\s*\{[\s\S]*?height: 100%/);
  assert.match(css, /\.run-report-visual-panel\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-visual-panel\s*\{[\s\S]*?overflow: hidden/);
  assert.match(css, /@media \(max-width: 1080px\)[\s\S]*?\.run-report-visual-panel\s*\{[\s\S]*?height: min\(42rem, calc\(100svh - 8rem\)\)/);
  assert.match(css, /\.run-report-evidence-card\s*\{[\s\S]*?height: 100%/);
  assert.match(css, /\.run-report-evidence-card\s*\{[\s\S]*?grid-template-rows: minmax\(0, 1fr\)/);
  assert.match(css, /\.run-report-browser\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-report-browser\s*\{[\s\S]*?box-shadow: inset 0 0 0 1px #e5e7eb/);
  assert.match(viewer, /run-report-browser__header/);
  assert.match(css, /\.run-report-browser__header\s*\{[\s\S]*?height: 2\.15rem/);
  assert.match(css, /\.run-report-browser__header span:first-child\s*\{[\s\S]*?width: 5\.8rem/);
  assert.doesNotMatch(viewer, /run-report-browser__bar/);
  assert.doesNotMatch(viewer, /run-report-browser__dots/);
  assert.doesNotMatch(css, /\.run-report-browser__bar/);
  assert.doesNotMatch(css, /\.run-report-browser__dots/);
  assert.doesNotMatch(viewer, /run-report-browser__address/);
  assert.doesNotMatch(css, /\.run-report-browser__address/);
  assert.doesNotMatch(viewer, /browserModeLabel/);
  assert.doesNotMatch(viewer, /run-report-browser__mode-pill/);
  assert.doesNotMatch(css, /\.run-report-browser__mode-pill/);
  assert.match(css, /\.run-report-insight-panel\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-report-insight-panel\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-insight-panel\s*\{[\s\S]*?box-shadow: 0 18px 46px rgba\(148, 163, 184, 0\.14\)/);
  assert.match(css, /\.run-report-insight-summary\s*\{[\s\S]*?position: sticky/);
  assert.match(css, /\.run-report-insight-summary__label h2\s*\{[\s\S]*?font-size: 0\.66rem/);
  assert.match(css, /\.run-report-insight-summary__label h2\s*\{[\s\S]*?color: #475569/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section\s*\{[\s\S]*?scroll-margin-top: 3\.7rem/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section \+ \.run-report-section\s*\{[\s\S]*?box-shadow: inset 0 1px 0 var\(--run-report-line-soft\)/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section--top-findings\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-insight-panel > \.run-report-section--priority\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-section-heading h3\s*\{[\s\S]*?font-size: 0\.66rem/);
  assert.match(css, /\.run-report-section-heading h3\s*\{[\s\S]*?color: #475569/);
  assert.match(css, /\.run-report-section-heading--compact\s*\{[\s\S]*?margin-bottom: 0/);
  assert.doesNotMatch(css, /\.run-report-insight-nav/);
  assert.doesNotMatch(css, /\.run-report-section-heading h2/);
  assert.doesNotMatch(css, /\.run-report-section-heading span/);
  assert.doesNotMatch(css, /\.run-report-insight-summary__label span/);
  assert.doesNotMatch(css, /\.run-report-section-heading--plain/);
  assert.doesNotMatch(css, /\.run-report-nudge-card__/);
  assert.doesNotMatch(css, /!important/);
  assert.match(css, /\.run-report-recommendation-picker\s*\{[\s\S]*?gap: 0\.72rem/);
  assert.match(css, /\.run-report-recommendation-tabs\s*\{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.run-report-recommendation-tab\s*\{[\s\S]*?min-height: 6\.05rem/);
  assert.match(css, /\.run-report-recommendation-tab\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-report-recommendation-tab--active\s*\{[\s\S]*?background: #f0f9ff/);
  assert.match(css, /\.run-report-recommendation-tab--active\s*\{[\s\S]*?box-shadow: none/);
  assert.match(css, /\.run-report-all-recommendations__toggle\s*\{[\s\S]*?border-radius: 999px/);
  assert.match(css, /\.run-report-all-recommendations__panel\s*\{[\s\S]*?max-height: 0/);
  assert.match(css, /\.run-report-all-recommendations__panel\s*\{[\s\S]*?pointer-events: none/);
  assert.match(css, /\.run-report-all-recommendations__panel\s*\{[\s\S]*?transition: max-height 240ms cubic-bezier/);
  assert.match(css, /\.run-report-all-recommendations__panel--open\s*\{[\s\S]*?max-height: 24rem/);
  assert.match(css, /\.run-report-all-recommendations__panel--open\s*\{[\s\S]*?pointer-events: auto/);
  assert.match(css, /\.run-report-all-recommendations__row\s*\{[\s\S]*?grid-template-columns: 1\.9rem minmax\(0, 1fr\) max-content/);
  assert.match(css, /\.run-report-all-recommendations__row--active\s*\{[\s\S]*?background: #f0f9ff/);
  assert.match(css, /\.run-report-selected-action\s*\{[\s\S]*?gap: 0\.85rem/);
  assert.match(css, /\.run-report-selected-action__summary\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-report-selected-action h2\s*\{[\s\S]*?font-size: 0\.82rem/);
  assert.match(css, /\.run-report-selected-action h2\s*\{[\s\S]*?font-weight: 760/);
  assert.match(css, /\.run-report-selected-action__details\s*\{[\s\S]*?gap: 0\.58rem/);
  assert.match(css, /\.run-report-selected-action__detail-card--primary\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-report-selected-action__detail-card--primary p\s*\{[\s\S]*?font-weight: 760/);
  assert.doesNotMatch(css, /\.run-report-selected-action__location/);
  assert.doesNotMatch(css, /\.run-report-selected-action__steps/);
  assert.match(css, /\.run-report-stage-group\s*\{[\s\S]*?gap: 0\.55rem/);
  assert.doesNotMatch(css, /\.run-report-stage-group__title/);
  assert.match(css, /\.run-report-stage-chips\s*\{[\s\S]*?display: block/);
  assert.match(css, /\.run-report-stage-chips\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-report-stage-chips\s*\{[\s\S]*?padding: 0\.5rem/);
  assert.match(css, /\.run-report-stage-chips ol\s*\{[\s\S]*?gap: 0/);
  assert.match(css, /\.run-report-stage-chips li\s*\{[\s\S]*?flex: 1 1 0/);
  assert.match(css, /\.run-report-stage-chips li \+ li\s*\{[\s\S]*?padding-left: 1rem/);
  assert.match(css, /\.run-report-stage-chips li \+ li::before\s*\{[\s\S]*?content: '→'/);
  assert.match(css, /\.run-report-stage-chips__item--active\s*\{[\s\S]*?flex-grow: 1/);
  assert.match(css, /\.run-report-stage-chip\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-stage-chip\s*\{[\s\S]*?border-radius: 0\.58rem/);
  assert.match(css, /\.run-report-stage-chip\s*\{[\s\S]*?white-space: nowrap/);
  assert.match(css, /\.run-report-stage-chip\s*\{[\s\S]*?text-overflow: ellipsis/);
  assert.match(css, /\.run-report-stage-chip--active\s*\{[\s\S]*?border-color: transparent/);
  assert.match(css, /\.run-report-stage-chip--active\s*\{[\s\S]*?background: #e0f2fe/);
  assert.doesNotMatch(css, /runReportStageChipGlow/);
  assert.match(css, /\.run-report-selected-action__summary\s*\{[\s\S]*?box-shadow: none/);
  assert.match(css, /\.run-report-selected-action__detail-card\s*\{[\s\S]*?background: #f8fafc/);
  assert.doesNotMatch(css.match(/\.run-report-nudge-empty\s*\{[^}]*\}/)?.[0] ?? '', /border-left/);
  assert.doesNotMatch(css, /\.run-report-nudge-empty::before/);
  assert.match(css, /\.run-report-evidence-preview\s*\{[\s\S]*?flex: 1[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-evidence-preview--image\s*\{[\s\S]*?overflow-y: auto/);
  assert.match(css, /\.run-report-evidence-preview__canvas\s*\{[\s\S]*?position: relative/);
  assert.match(css, /\.run-report-evidence-preview__canvas\s*\{[\s\S]*?width: 100%/);
  assert.doesNotMatch(css.match(/\.run-report-evidence-preview__canvas\s*\{[^}]*\}/)?.[0] ?? '', /min-height:\s*100%/);
  assert.match(css, /\.run-report-friction-marker\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-report-friction-marker::before\s*\{[\s\S]*?border-radius: 999px/);
  assert.match(css, /\.run-report-friction-marker::before\s*\{[\s\S]*?rgba\(245, 158, 11, 0\.72\)/);
  assert.match(css, /\.run-report-friction-marker span\s*\{[\s\S]*?background: #78350f/);
  assert.match(css, /\.run-report-friction-marker span\s*\{[\s\S]*?font-size: 0\.62rem/);
  assert.match(css, /\.run-report-friction-marker span\s*\{[\s\S]*?text-transform: none/);
  assert.doesNotMatch(css, /runReportMarkerRipple|runReportMarkerBreath/);
  assert.doesNotMatch(css.match(/\.run-report-friction-marker\s*\{[^}]*\}/)?.[0] ?? '', /#0ea5e9/);
  assert.match(css, /\.run-report-evidence-preview__image\s*\{[\s\S]*?height: auto/);
  assert.match(css, /\.run-report-evidence-preview__blank\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-report-evidence-preview--resolving\s*\{[\s\S]*?background: #fff/);
  assert.doesNotMatch(viewer, /run-report-evidence-preview__hero|report\.heroTitle|report\.heroSubtitle|report\.heroCallToAction/);
  assert.match(css, /\.run-report-topbar__link\s*\{[\s\S]*?background: #334155/);
  assert.match(css, /\.run-report-state-card a,\s*\n\.run-report-state-card button\s*\{[\s\S]*?background: #334155/);
  assert.match(css, /\.run-report-state-card__header\s*\{[\s\S]*?margin-bottom: 1rem/);
  assert.doesNotMatch(css, /\.run-report-state-card::before/);
  assert.doesNotMatch(css, /\.run-report-state-card > span/);
  assert.match(css, /\.run-report-state-card__actions a\s*\{[\s\S]*?background: rgba\(240, 249, 255, 0\.88\)/);
  assert.match(css, /\.run-report-state-card__meta\s*\{[\s\S]*?border-top: 1px solid #f1f5f9/);
  assert.doesNotMatch(css, /\.run-report-loading-status/);
  assert.doesNotMatch(css, /\.run-report-skeleton-line/);
  assert.doesNotMatch(css, /@keyframes runReportSkeletonPulse/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.run-report-recommendation-tabs\s*\{[\s\S]*?grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.run-report-all-recommendations__row\s*\{[\s\S]*?grid-template-columns: 1fr/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.run-report-all-recommendations__panel\s*\{[\s\S]*?transition: none/);
  assert.doesNotMatch(css, /run-report-side-column/);
  assert.doesNotMatch(css, /run-report-action-card/);
  assert.doesNotMatch(css, /run-report-stage-strip/);
  assert.doesNotMatch(css, /run-report-stage-context/);
  assert.doesNotMatch(css, /run-report-stage-chips__eyebrow/);
  assert.doesNotMatch(css, /run-report-selected-action__topline/);
  assert.doesNotMatch(css, /run-report-conversion-flow/);
  assert.doesNotMatch(css, /run-report-decision-map/);
  assert.doesNotMatch(css, /run-report-primary-nudge/);
  assert.doesNotMatch(css, /run-report-next-nudges/);
  assert.doesNotMatch(css, /run-report-reason-card/);
  assert.doesNotMatch(css, /run-report-validation-check/);
  assert.doesNotMatch(css, /run-report-finding-row/);
  assert.match(css, /@media \(max-width: 1080px\)/);
  assert.match(css, /@media \(max-width: 760px\)/);
});

test('authenticated resource hook avoids raw api image urls and cleans blob urls', () => {
  const source = fs.readFileSync(
    new URL('../../src/shared/lib/authenticatedResourceUrl.ts', import.meta.url),
    'utf8',
  );

  assert.match(source, /useState<string \\| null>\(null\)/);
  assert.doesNotMatch(source, /useState<string \\| null>\(resourceUrl \?\? null\)/);
  assert.match(source, /URL\.createObjectURL\(blob\)/);
  assert.match(source, /URL\.revokeObjectURL\(objectUrl\)/);
  assert.match(source, /\.catch\(\(\) => \{[\s\S]*?setResolvedUrl\(null\)/);
});

test('run monitor exposes a report CTA into /runs/:runId/report', () => {
  const source = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.tsx', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.css', import.meta.url), 'utf8');

  assert.match(source, /import \{ handleSpaNavigationClick, replaceAppPath \}/);
  assert.match(source, /import \{ buildRunReportPath \}/);
  assert.match(source, /const reportCtaState = resolveRunMonitorReportCtaState/);
  assert.match(source, /const reportPath = reportCtaState\.canOpenReport[\s\S]*buildRunReportPath\(run\.id/);
  assert.match(source, /getRunReport\(run\.id\)/);
  assert.match(source, /generateRunReport\(requestedRunId\)/);
  assert.match(source, /requestRunAnalysis\(requestedRunId\)/);
  assert.match(source, /reportCtaState\.titleLabel/);
  assert.match(source, /reportCtaState\.kind !== 'hidden'/);
  assert.match(source, /분석 결과 리포트/);
  assert.match(source, /handleSpaNavigationClick\(event, reportPath\)/);
  assert.match(source, /run-monitor-report-cta--clickable/);
  assert.match(source, /<a[\s\S]*?href=\{reportPath\}[\s\S]*?onClick=\{openReport\}[\s\S]*?>/);
  assert.match(source, /리포트 열기/);
  assert.match(source, /리포트 준비 중/);
  assert.doesNotMatch(source, /리포트 보기/);
  assert.doesNotMatch(source, /'리포트 생성'/);
  assert.doesNotMatch(source, /'분석 시작'/);
  assert.doesNotMatch(source, /모의 리포트 보기/);
  assert.match(css, /\.run-monitor-report-cta\s*\{[\s\S]*?background: rgba\(240, 249, 255, 0\.58\)/);
  assert.match(css, /\.run-monitor-report-cta\s*\{[\s\S]*?text-decoration: none/);
  assert.match(css, /\.run-monitor-report-cta--clickable\s*\{[\s\S]*?cursor: pointer/);
  assert.match(css, /\.run-monitor-report-cta__open-label::after\s*\{[\s\S]*?content: '→'/);
  assert.match(css, /\.run-monitor-report-cta__passive-label\s*\{[\s\S]*?color: #94a3b8/);
  assert.doesNotMatch(css, /\.run-monitor-report-cta__passive-label::after/);
  assert.doesNotMatch(css, /\.run-monitor-report-cta__actions a:hover/);
  assert.match(css, /\.run-monitor-report-cta__actions button\s*\{[\s\S]*?background: #475569/);
  assert.match(css, /\.run-monitor-report-cta__actions button\s*\{[\s\S]*?width: 100%/);
  assert.match(css, /\.run-monitor-report-cta__actions button:disabled\s*\{[\s\S]*?cursor: not-allowed/);
});
