server {
    listen 80;
    server_name wedge-jenkins.duckdns.org;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 200 "jenkins certbot challenge ready\n";
    }
}
