from __future__ import annotations

RULE_SEMANTIC_CONFIDENCE_MIN = 0.60

SCENARIO_RELEVANCE_SCORES = {
    "DIRECT_GOAL_ACTION": 1.0,
    "RELATED_GOAL_ACTION": 0.8,
    "PREREQUISITE_ACTION": 0.6,
    "EXPLORATORY_ACTION": 0.4,
    "AUXILIARY_ACTION": 0.2,
    "IRRELEVANT_ACTION": 0.0,
}

ACTION_SPECIFICITY_SCORES = {
    "SPECIFIC_ACTION": 1.0,
    "GENERIC_BUT_ACTIONABLE": 0.8,
    "PROGRESSION_ONLY": 0.6,
    "EXPLORATORY_LABEL": 0.4,
    "WEAK_OR_ICON_ONLY": 0.2,
    "NO_LABEL": 0.0,
}
