spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

wedge:
  runner:
    mq:
      exchange: ${WEDGE_RUNNER_MQ_EXCHANGE:wedge.direct}
      run-execute-queue: ${WEDGE_RUN_EXECUTE_QUEUE:run.execute.request}
  internal:
    service-token: ${INTERNAL_SERVICE_TOKEN}
