import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

function cssRule(css: string, selector: string) {
  const start = css.indexOf(`${selector} {`);

  assert.notEqual(start, -1, `Missing CSS rule for ${selector}`);

  const end = css.indexOf('\n}', start);

  assert.notEqual(end, -1, `Missing CSS rule close for ${selector}`);

  return css.slice(start, end);
}

test('app routes /runs/:runId to the run monitor page', () => {
  const source = fs.readFileSync(new URL('../../src/app/App.tsx', import.meta.url), 'utf8');
  const pages = fs.readFileSync(new URL('../../src/pages/index.ts', import.meta.url), 'utf8');

  assert.match(pages, /pathPrefix: RUN_MONITOR_PATH_PREFIX/);
  assert.match(source, /import \{ resolveAppRoute, resolveProtectedRouteGate/);
  assert.match(source, /<RunMonitorPage runId=\{route\.runId\} \/>/);
});

test('run monitor page exposes Sprint 2 live cockpit essentials with Korean-facing labels', () => {
  const source = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.tsx', import.meta.url), 'utf8');
  const stateHook = fs.readFileSync(new URL('../../src/features/run-monitor/lib/useRunMonitorState.ts', import.meta.url), 'utf8');
  const viewModel = fs.readFileSync(new URL('../../src/features/run-monitor/lib/runMonitorViewModel.ts', import.meta.url), 'utf8');

  assert.match(source, /실행 모니터/);
  assert.doesNotMatch(source, /실시간 시뮬레이션/);
  assert.match(source, /대상/);
  assert.match(source, /href=\{RUNS_PATH\}/);
  assert.match(source, />실행 목록<\/a>/);
  assert.match(source, /실행 ID/);
  assert.match(source, /디바이스/);
  assert.match(source, /시나리오 경로/);
  assert.doesNotMatch(source, /진행 요약/);
  assert.match(source, /전체 진행률/);
  assert.match(viewModel, /현재 체크포인트/);
  assert.match(viewModel, /리포트 준비 완료/);
  assert.match(source, /currentCheckpoint/);
  assert.match(source, /getLiveInsightMessage/);
  assert.match(source, /실행 중 오류가 발생해 근거 수집이 중단됐습니다/);
  assert.match(stateHook, /EVIDENCE_LOAD_RUN_STATUSES = new Set\(\[\'COMPLETED\', \'FAILED\', \'STOPPED\'\]\)/);
  assert.doesNotMatch(source, /<p>선택한 흐름을 준비하고 있습니다\. 곧 근거 수집을 시작합니다\.<\/p>/);
  assert.doesNotMatch(source, /shouldShowSimulationCheckpoint/);
  assert.doesNotMatch(source, /run-monitor-simulation__header/);
  assert.match(source, /<section className="run-monitor-simulation" aria-label="최근 화면 캡처">/);
  assert.match(source, /useRunMonitorState\(runId, mockData, isMockRun\)/);
  assert.match(stateHook, /getRun\(runId\)/);
  assert.match(stateHook, /getRunLive\(runId\)/);
  assert.match(stateHook, /listRunSteps\(runId\)/);
  assert.match(stateHook, /listRunEvents\(runId, \{ limit: 50 \}\)/);
  assert.match(stateHook, /getRunEvidencePacket\(runId\)/);
  assert.match(stateHook, /evidencePacket/);
  assert.match(stateHook, /isEvidenceLoading/);
  assert.match(stateHook, /clearEvidenceState\(\);[\s\S]*?setRunSteps\(\[\]\);[\s\S]*?setRunEvents\(\[\]\);/);
  assert.match(stateHook, /window\.setTimeout\(\(\) => void loadRunState\(false\), RUN_MONITOR_REFRESH_INTERVAL_MS\)/);
  assert.match(stateHook, /shouldRefreshRunLive\(liveResponse\.data\.status\)/);
  assert.match(source, /visibleSteps\.map/);
  assert.doesNotMatch(source, /visibleLogs\.map/);
  assert.doesNotMatch(source, /function LogMarker/);
  assert.doesNotMatch(source, /run-monitor-log__/);
  assert.match(source, /run-monitor-step__status/);
  assert.match(source, /실제 실행 상태/);
  assert.match(source, /buildApiEventTimeline/);
  assert.match(viewModel, /buildApiStepTimeline/);
  assert.match(source, /실제 실행 이벤트를 바탕으로 확인한 경로입니다/);
  assert.match(source, /화면 캡처 대기 중/);
  assert.match(source, /수집 요약/);
  assert.match(source, /RunContextBar/);
  assert.match(source, /RunCollectionSummary/);
  assert.match(source, /buildRunCollectionSummaryStats/);
  assert.match(source, /const isCurrentRunSnapshot = run\.id === runId && live\.runId === runId/);
  assert.match(source, /evidencePacket\?\.run_id === runId/);
  assert.match(source, /runSteps\.filter\(\(step\) => step\.runId === runId\)/);
  assert.match(source, /runEvents\.filter\(\(event\) => event\.runId === runId\)/);
  assert.match(source, /buildApiEventTimeline\(run, live, currentRunEvents, currentRunSteps\)/);
  assert.match(source, /URL 기준 방문/);
  assert.match(source, /스크린샷/);
  assert.match(source, /실행 step/);
  assert.doesNotMatch(source, /<dt>체크<\/dt>/);
  assert.doesNotMatch(source, /<dt>신호<\/dt>/);
  assert.doesNotMatch(source, /<dt>자료<\/dt>/);
  assert.match(viewModel, /checkpoint\.artifact_refs/);
  assert.match(source, /getEvidenceScreenshotPreviewUrl/);
  assert.match(source, /formatDisplayUrl/);
  assert.match(source, /const targetUrlLabel = formatDisplayUrl\(targetUrl\)/);
  assert.match(source, /<strong title=\{targetUrl\}>\{targetUrlLabel\}<\/strong>/);
  assert.match(source, /const snapshotUrl = evidenceScreenshotUrl \?\? live\.latestFrame\?\.url \?\? run\.latestSnapshot\?\.url/);
  assert.match(source, /useAuthenticatedResourceUrl\(snapshotUrl\)/);
  assert.match(source, /const authenticatedSnapshotUrl = useAuthenticatedResourceUrl\(snapshotUrl\);[\s\S]*?if \(isRealRunLoading\)/);
  assert.match(source, /src=\{authenticatedSnapshotUrl\}/);
  assert.match(stateHook, /실행 상태를 불러오지 못했습니다/);
  assert.match(source, /RunMonitorStatePage/);
  assert.match(source, /function RunMonitorLoadingShell/);
  assert.match(source, /if \(isRealRunLoading\) \{[\s\S]*?<RunMonitorLoadingShell runId=\{runId\} targetUrl=\{fallbackUrl\} \/>/);
  assert.match(source, /run-monitor-page run-monitor-page--loading/);
  assert.match(source, /role="status">실제 실행 데이터를 연결하고 있습니다\./);
  assert.doesNotMatch(source, /title="실행 상태를 불러오는 중입니다"/);
  assert.match(source, /role="progressbar"/);
  assert.match(source, /aria-valuenow=\{progressPercent\}/);
  assert.match(source, /run-monitor-agent-pointer/);
  assert.match(source, /run-monitor-scan-line/);
  assert.match(source, /run-monitor-detection-box/);
  assert.match(source, /run-monitor-browser__header/);
  assert.doesNotMatch(source, /run-monitor-browser__address/);
  assert.doesNotMatch(source, /run-monitor-browser__bar/);
  assert.doesNotMatch(source, /run-monitor-browser__dots/);
  assert.match(source, /run-monitor-mock-cta/);
  assert.doesNotMatch(source, /모의 프리뷰/);
  assert.doesNotMatch(source, /페이지 캡처/);
  assert.doesNotMatch(source, /실제 캡처/);
  assert.match(source, /선택한 흐름/);
  assert.match(source, /확인 범위/);
  assert.match(source, /getDepthLabel/);
  assert.match(source, /getDevicePresetLabel/);
  assert.match(source, /canRequestRunStop\(live\.status\)/);
  assert.match(source, /canRequestRunDelete\(live\.status\)/);
  assert.match(source, /stopRun\(run\.id/);
  assert.match(source, /중지 요청을 보내고 있어요\./);
  assert.match(source, /중지 요청을 보냈어요\. 상태가 갱신되면 자동으로 반영됩니다\./);
  assert.match(source, /중지 요청을 보내지 못했어요\. 권한 또는 서버 상태를 확인해주세요\./);
  assert.match(source, /이 실행을 삭제할까요\? 삭제하면 실행 목록으로 이동합니다\./);
  assert.match(source, /삭제 요청을 보내고 있어요\./);
  assert.match(source, /삭제 요청을 보내지 못했어요\. 권한 또는 서버 상태를 확인해주세요\./);
  assert.doesNotMatch(source, /Run 중지 요청/);
  assert.doesNotMatch(source, /이 Run을 삭제/);
  assert.doesNotMatch(source, /Run 삭제/);
  assert.match(source, /window\.confirm/);
  assert.match(source, /deleteRun\(run\.id\)/);
  assert.match(source, /className="run-monitor-lifecycle-actions__stop"/);
  assert.match(source, /className="run-monitor-lifecycle-actions__delete"/);
  assert.match(source, /getRunReport\(run\.id\)/);
  assert.match(source, /generateRunReport\(requestedRunId\)/);
  assert.match(source, /requestRunAnalysis\(requestedRunId\)/);
  assert.match(source, /replaceAppPath\(RUNS_PATH\)/);
  assert.match(source, /handleSpaNavigationClick\(event, reportPath\)/);
  assert.match(source, /resolveRunMonitorReportCtaState/);
  assert.match(source, /const shouldRefreshCurrentReport = shouldRefreshRunReport\(currentReportProjection\)/);
  assert.match(source, /RUN_MONITOR_REFRESH_INTERVAL_MS/);
  assert.match(source, /activeRouteRunIdRef/);
  assert.match(source, /autoReportAnalysisRunIdRef/);
  assert.match(source, /autoReportGenerationRunIdRef/);
  assert.match(source, /isMonitorMountedRef/);
  assert.match(source, /canApplyReportResponse\(requestedRunId\)/);
  assert.match(source, /requestAnalysisForRun\(run\.id\)/);
  assert.match(source, /generateReportForRun\(run\.id\)/);
  assert.match(source, /reportCtaState\.kind === 'generate'/);
  assert.match(source, /reportCtaState\.kind === 'request-analysis'/);
  assert.doesNotMatch(source, /reportCtaStatusLabel/);
  assert.match(source, /reportCtaCardClassName/);
  assert.match(source, /run-monitor-report-cta--clickable/);
  assert.match(source, /<a[\s\S]*?href=\{reportPath\}[\s\S]*?onClick=\{openReport\}[\s\S]*?>/);
  assert.match(source, /run-monitor-report-cta__actions/);
  assert.match(source, /run-monitor-report-cta__open-label/);
  assert.match(source, /run-monitor-report-cta__open-text/);
  assert.match(source, /run-monitor-report-cta__open-icon/);
  assert.match(source, /width=\{18\} height=\{18\}/);
  assert.match(source, /M1\.946 9\.315/);
  assert.doesNotMatch(source, /run-monitor-report-cta__complete-mark/);
  assert.doesNotMatch(source, /run-monitor-report-cta__passive-label/);
  assert.match(source, /RunMonitorGooLoader/);
  assert.match(source, /RunMonitorShapeLoader/);
  assert.match(source, /run-monitor-browser__loading-state/);
  assert.match(source, /화면 캡처를 기다리고 있습니다/);
  assert.match(source, /분석 결과를 확인 중입니다/);
  assert.match(source, /리포트를 준비 중입니다/);
  assert.match(source, /상태를 확인 중입니다/);
  assert.match(source, /리포트 열기/);
  assert.doesNotMatch(source, /리포트 보기/);
  assert.match(source, /RUN_MONITOR_PANEL_DEFAULT_WIDTH/);
  assert.match(source, /RUN_MONITOR_PANEL_DEFAULT_RATIO = 0\.4/);
  assert.match(source, /RUN_MONITOR_PANEL_MAX_WIDTH = 560/);
  assert.match(source, /RUN_MONITOR_RESIZER_FALLBACK_WIDTH = 8/);
  assert.match(source, /useResizableTrailingPanel\(cockpitRef/);
  assert.match(source, /leadMinWidth: RUN_MONITOR_CAPTURE_MIN_WIDTH/);
  assert.match(source, /maxWidth: RUN_MONITOR_PANEL_MAX_WIDTH/);
  assert.match(source, /resetKey: `\$\{isRealRunLoading\}:\$\{runId\}`/);
  assert.match(source, /handleAnalysisPanelResizePointerDown/);
  assert.match(source, /run-monitor-cockpit run-monitor-cockpit--resizable/);
  assert.match(source, /run-monitor-panel-resizer/);
  assert.match(source, /리포트 준비 중/);
  assert.match(source, /다시 시도/);
  assert.doesNotMatch(source, /'리포트 생성'/);
  assert.doesNotMatch(source, /'분석 시작'/);
  assert.match(source, /RunLifecycleActions/);
  assert.match(viewModel, /데스크톱/);
  assert.doesNotMatch(source, /<button type="button">\{mockData\.previewCallToAction\}<\/button>/);
});

test('run monitor css follows the live cockpit visual language', () => {
  const source = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.tsx', import.meta.url), 'utf8');
  const css = fs.readFileSync(new URL('../../src/pages/run-monitor/RunMonitorPage.css', import.meta.url), 'utf8');

  assert.match(css, /\.run-monitor-page\s*\{[\s\S]*?background: #fff/);
  assert.match(cssRule(css, '.run-monitor-workspace'), /display: grid/);
  assert.match(cssRule(css, '.run-monitor-workspace'), /grid-template-rows: auto minmax\(0, 1fr\)/);
  assert.match(css, /\.run-monitor-run-context\s*\{[\s\S]*?border-bottom: 1px solid #f1f5f9/);
  assert.match(css, /\.run-monitor-cockpit\s*\{[\s\S]*?grid-template-columns: minmax\(0, 1fr\) 28rem/);
  assert.match(css, /\.run-monitor-cockpit--resizable\s*\{[\s\S]*?grid-template-columns: minmax\(0, 1fr\) 0\.5rem minmax\(21rem, var\(--run-monitor-analysis-panel-width, 28rem\)\)/);
  assert.match(cssRule(css, '.run-monitor-cockpit'), /align-self: stretch/);
  assert.match(cssRule(css, '.run-monitor-panel-resizer'), /cursor: col-resize/);
  assert.match(cssRule(css, '.run-monitor-panel-resizer'), /touch-action: none/);
  assert.match(cssRule(css, '.run-monitor-simulation'), /min-height: 0/);
  assert.match(cssRule(css, '.run-monitor-simulation'), /overflow: hidden/);
  assert.match(cssRule(css, '.run-monitor-analysis-panel'), /display: flex/);
  assert.match(cssRule(css, '.run-monitor-analysis-panel'), /align-self: stretch/);
  assert.match(cssRule(css, '.run-monitor-analysis-panel'), /overflow: hidden/);
  assert.match(cssRule(css, '.run-monitor-panel-scroll'), /height: 0/);
  assert.match(cssRule(css, '.run-monitor-panel-scroll'), /flex: 1 1 0/);
  assert.match(cssRule(css, '.run-monitor-panel-scroll'), /overflow-y: auto/);
  assert.match(css, /\.run-monitor-browser\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-monitor-browser\s*\{[\s\S]*?box-shadow: inset 0 0 0 1px #e5e7eb/);
  assert.match(css, /\.run-monitor-browser__header\s*\{[\s\S]*?height: 2\.15rem/);
  assert.match(css, /\.run-monitor-browser__header span:first-child\s*\{[\s\S]*?width: 5\.8rem/);
  assert.doesNotMatch(css, /\.run-monitor-browser__address/);
  assert.doesNotMatch(css, /\.run-monitor-browser__mode-pill/);
  assert.doesNotMatch(css, /\.run-monitor-browser__bar/);
  assert.doesNotMatch(css, /\.run-monitor-browser__dots/);
  assert.match(css, /\.run-monitor-target-inline span\s*\{[\s\S]*?color: #94a3b8/);
  assert.match(css, /\.run-monitor-target-inline span\s*\{[\s\S]*?font-size: 0\.56rem/);
  assert.doesNotMatch(css, /\.run-monitor-target-inline \+ \.run-monitor-target-inline::before/);
  assert.match(css, /\.run-monitor-topbar__link--secondary\s*\{[\s\S]*?color: #475569/);
  assert.match(css, /\.run-monitor-topbar__link--primary\s*\{[\s\S]*?background: #334155/);
  assert.match(cssRule(css, '.run-monitor-page'), /--run-monitor-complete-sky: #bae6fd/);
  assert.match(cssRule(css, '.run-monitor-page'), /--run-monitor-complete-sky-soft: #e0f2fe/);
  assert.match(cssRule(css, '.run-monitor-page'), /--run-monitor-complete-blue: #0284c7/);
  assert.match(cssRule(css, '.run-monitor-page'), /--run-monitor-report-cta-bg: #e0f2fe/);
  assert.match(cssRule(css, '.run-monitor-page'), /--run-monitor-report-cta-label: #334155/);
  assert.match(css, /\.run-monitor-status--complete,\s*\n\.run-monitor-status--queued\s*\{[\s\S]*?border-color: transparent/);
  assert.match(css, /\.run-monitor-status--complete,\s*\n\.run-monitor-status--queued\s*\{[\s\S]*?background: transparent/);
  assert.match(css, /\.run-monitor-status--complete,\s*\n\.run-monitor-status--queued\s*\{[\s\S]*?padding-right: 0\.2rem/);
  assert.match(css, /\.run-monitor-status--complete\s*\{[\s\S]*?color: var\(--run-monitor-complete-blue\)/);
  assert.match(css, /\.run-monitor-status--complete \.run-monitor-status__dot,\s*\n\.run-monitor-status--queued \.run-monitor-status__dot\s*\{[\s\S]*?width: 0\.32rem/);
  assert.match(css, /\.run-monitor-status--complete \.run-monitor-status__dot,\s*\n\.run-monitor-status--queued \.run-monitor-status__dot\s*\{[\s\S]*?height: 0\.32rem/);
  assert.match(css, /\.run-monitor-status--complete \.run-monitor-status__dot\s*\{[\s\S]*?background: var\(--run-monitor-complete-sky\)/);
  assert.match(css, /\.run-monitor-status--queued\s*\{[\s\S]*?color: #475569/);
  assert.match(css, /\.run-monitor-status--queued \.run-monitor-status__dot\s*\{[\s\S]*?background: #bae6fd/);
  assert.match(css, /\.run-monitor-status\s*\{[\s\S]*?font-size: 0\.68rem/);
  assert.match(css, /\.run-monitor-status\s*\{[\s\S]*?letter-spacing: 0\.06em/);
  assert.match(css, /\.run-monitor-target-inline strong\s*\{[\s\S]*?display: block/);
  assert.match(css, /\.run-monitor-target-inline strong\s*\{[\s\S]*?font-size: 0\.82rem/);
  assert.match(css, /\.run-monitor-target-inline strong\s*\{[\s\S]*?font-weight: 850/);
  assert.doesNotMatch(css, /run-monitor-section-title/);
  assert.doesNotMatch(css, /run-monitor-simulation__header/);
  assert.match(css, /\.run-monitor-panel-heading h2,[\s\S]*?\.run-monitor-timeline h2\s*\{[\s\S]*?color: #475569/);
  assert.doesNotMatch(source, /run-monitor-live-insight__label">\s*<span/);
  assert.doesNotMatch(css, /\.run-monitor-live-insight__label h2\s*\{[\s\S]*?color: #0369a1/);
  assert.doesNotMatch(css, /\.run-monitor-live-insight__label span/);
  assert.match(css, /\.run-monitor-step\s*\{[\s\S]*?border-radius: 0\.72rem/);
  assert.match(css, /\.run-monitor-step\s*\{[\s\S]*?transition: box-shadow 160ms ease, transform 160ms ease/);
  assert.match(css, /\.run-monitor-step:hover\s*\{[\s\S]*?box-shadow: 0 8px 18px rgba\(148, 163, 184, 0\.1\)/);
  assert.match(css, /\.run-monitor-step:hover\s*\{[\s\S]*?transform: translateY\(-1px\)/);
  assert.doesNotMatch(css, /\.run-monitor-step:hover\s*\{[^}]*border-color:/);
  assert.match(css, /\.run-monitor-step--complete:hover\s*\{[\s\S]*?box-shadow: 0 8px 18px rgba\(125, 211, 252, 0\.12\)/);
  assert.doesNotMatch(css, /\.run-monitor-step--complete:hover\s*\{[^}]*border-color:/);
  assert.match(css, /\.run-monitor-step__head h3\s*\{[\s\S]*?text-overflow: ellipsis/);
  assert.match(css, /\.run-monitor-step__status\s*\{[\s\S]*?border-radius: 999px/);
  assert.match(css, /\.run-monitor-step__content time\s*\{[\s\S]*?color: #cbd5e1/);
  assert.doesNotMatch(css, /run-monitor-log__/);
  assert.match(css, /\.run-monitor-collection-summary\s*\{[\s\S]*?display: grid/);
  assert.match(css, /\.run-monitor-collection-summary dl\s*\{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.run-monitor-collection-summary dl\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-monitor-collection-summary div\s*\{[\s\S]*?background: #f1f5f9/);
  assert.match(css, /\.run-monitor-agent-pointer\s*\{[\s\S]*?animation: runMonitorPointerMove/);
  assert.match(css, /\.run-monitor-scan-line\s*\{[\s\S]*?animation: runMonitorScanning/);
  assert.match(css, /\.run-monitor-detection-box\s*\{[\s\S]*?border: 1px dashed #0ea5e9/);
  assert.match(css, /\.run-monitor-state-card\s*\{[\s\S]*?box-shadow: 0 28px 80px/);
  assert.match(css, /\.run-monitor-mock-cta\s*\{[\s\S]*?background: #111827/);
  assert.match(css, /\.run-monitor-live-insight__card\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-monitor-browser__stage--loading-skeleton\s*\{[\s\S]*?animation: none/);
  assert.match(css, /\.run-monitor-goo-loader__dots\s*\{[\s\S]*?filter: url\("#run-monitor-goo-filter"\)/);
  assert.match(css, /\.run-monitor-goo-loader__dot--one\s*\{[\s\S]*?background-color: #bae6fd/);
  assert.match(css, /\.run-monitor-goo-loader__dot--two\s*\{[\s\S]*?background-color: #38bdf8/);
  assert.match(css, /\.run-monitor-goo-loader__dot--three\s*\{[\s\S]*?background-color: #334155/);
  assert.match(css, /\.run-monitor-report-cta\s*\{[\s\S]*?background: #fff/);
  assert.match(css, /\.run-monitor-report-cta\s*\{[\s\S]*?text-decoration: none/);
  assert.match(css, /\.run-monitor-report-cta\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-monitor-report-cta--clickable\s*\{[\s\S]*?cursor: pointer/);
  assert.match(css, /\.run-monitor-report-cta--clickable\s*\{[\s\S]*?-webkit-tap-highlight-color: transparent/);
  assert.doesNotMatch(css, /\.run-monitor-report-cta--clickable:hover\s*\{[\s\S]*?background: #fff/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable::after'), /right: 0\.86rem/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable::after'), /bottom: 0\.86rem/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable::after'), /width: 6\.1rem/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable::after'), /height: 1\.82rem/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable::after'), /background: var\(--run-monitor-report-cta-bg\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable::after'), /transform: scale\(1\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible)::after'), /opacity: 1/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible)::after'), /transform: scale\(22\)/);
  assert.match(css, /@media \(hover: hover\) \{[\s\S]*?\.run-monitor-report-cta--clickable:hover::after\s*\{[\s\S]*?transform: scale\(22\)/);
  assert.match(css, /\.run-monitor-report-cta--clickable:focus-visible\s*\{[\s\S]*?outline: 2px solid rgba\(14, 165, 233, 0\.42\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta--open::before'), /animation: run-monitor-report-diagonal-glass-sheen 3\.2s ease-in-out infinite/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible)::before'), /animation: none/);
  assert.doesNotMatch(css, /run-monitor-report-cta__complete-mark/);
  assert.doesNotMatch(css, /run-monitor-report-check-pop/);
  assert.doesNotMatch(css, /run-monitor-report-check-draw/);
  assert.doesNotMatch(css, /\.run-monitor-report-cta__state/);
  assert.match(css, /\.run-monitor-report-cta > p\s*\{[\s\S]*?min-height: 0/);
  assert.match(cssRule(css, '.run-monitor-report-cta__activity'), /display: flex/);
  assert.doesNotMatch(cssRule(css, '.run-monitor-report-cta__activity'), /background:/);
  assert.match(cssRule(css, '.run-monitor-shape-loader__shape'), /linear-gradient\(-45deg, var\(--run-monitor-complete-sky\) 0%, var\(--run-monitor-complete-sky-soft\) 48%, #0ea5e9 100%\)/);
  assert.match(cssRule(css, '.run-monitor-shape-loader__shape'), /animation: run-monitor-shape-loader-spin 3s infinite/);
  assert.match(css, /\.run-monitor-report-cta__footer\s*\{[\s\S]*?display: grid/);
  assert.match(css, /\.run-monitor-report-cta__footer\s*\{[\s\S]*?border-top: 0/);
  assert.match(css, /\.run-monitor-report-cta__actions\s*\{[\s\S]*?width: 100%/);
  assert.match(css, /\.run-monitor-report-cta__actions\s*\{[\s\S]*?justify-content: flex-end/);
  assert.match(css, /\.run-monitor-report-cta__open-label\s*\{[\s\S]*?color: var\(--run-monitor-report-cta-label\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-label'), /background: var\(--run-monitor-report-cta-bg\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-label'), /overflow: hidden/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-label'), /transition: transform 200ms ease/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-text'), /color: var\(--run-monitor-report-cta-label\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-text'), /transition: transform 300ms ease-in-out, opacity 220ms ease-in-out/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-text'), /margin-left: 0\.3em/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-icon'), /color: var\(--run-monitor-report-cta-label\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-icon svg'), /color: var\(--run-monitor-report-cta-label\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta .run-monitor-report-cta__open-text,\n.run-monitor-report-cta .run-monitor-report-cta__open-icon,\n.run-monitor-report-cta .run-monitor-report-cta__open-icon svg'), /color: var\(--run-monitor-report-cta-label\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta__open-icon svg'), /transition: transform 300ms ease-in-out/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible) .run-monitor-report-cta__open-icon'), /animation: run-monitor-report-open-fly 600ms ease-in-out infinite alternate/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible) .run-monitor-report-cta__open-icon svg'), /transform: translateX\(2\.8em\) rotate\(45deg\) scale\(1\.1\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible) .run-monitor-report-cta__open-text'), /opacity: 0/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:is(:active, :focus-visible) .run-monitor-report-cta__open-text'), /transform: translateX\(6\.4em\)/);
  assert.match(cssRule(css, '.run-monitor-report-cta--clickable:active .run-monitor-report-cta__open-label'), /transform: scale\(0\.95\)/);
  assert.match(css, /@keyframes run-monitor-report-open-fly/);
  assert.match(css, /transform: translate\(0\.08em, 0\.08em\)/);
  assert.match(css, /transform: translate\(0\.48em, -0\.08em\)/);
  assert.doesNotMatch(css, /\.run-monitor-report-cta__passive-label/);
  assert.doesNotMatch(css, /\.run-monitor-report-cta__actions a:hover/);
  assert.match(css, /\.run-monitor-report-cta__actions button\s*\{[\s\S]*?background: #475569/);
  assert.match(css, /\.run-monitor-report-cta__actions button\s*\{[\s\S]*?width: 100%/);
  assert.match(css, /\.run-monitor-report-cta__actions button\s*\{[\s\S]*?justify-content: center/);
  assert.match(css, /\.run-monitor-report-cta__actions button\s*\{[\s\S]*?min-height: 1\.92rem/);
  assert.match(css, /\.run-monitor-report-cta__status--error\s*\{[\s\S]*?color: #c2410c/);
  assert.match(css, /\.run-monitor-report-cta__actions button:disabled\s*\{[\s\S]*?cursor: not-allowed/);
  assert.match(css, /\.run-monitor-lifecycle-actions button\s*\{[\s\S]*?height: 2\.05rem/);
  assert.match(css, /\.run-monitor-lifecycle-actions button\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-monitor-lifecycle-actions button\s*\{[\s\S]*?font-size: 0\.68rem/);
  assert.match(css, /\.run-monitor-lifecycle-actions button\s*\{[\s\S]*?letter-spacing: 0\.06em/);
  assert.match(css, /\.run-monitor-lifecycle-actions button:hover:not\(:disabled\)\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__stop\s*\{[\s\S]*?background: #fffaf2/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__stop\s*\{[\s\S]*?color: #9a6a2f/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__stop:hover:not\(:disabled\)\s*\{[\s\S]*?background: #fff4df/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__stop:hover:not\(:disabled\)\s*\{[\s\S]*?color: #80551d/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__delete\s*\{[\s\S]*?background: #fff9fa/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__delete\s*\{[\s\S]*?color: #a65f68/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__delete:hover:not\(:disabled\)\s*\{[\s\S]*?background: #fff1f3/);
  assert.match(css, /\.run-monitor-lifecycle-actions \.run-monitor-lifecycle-actions__delete:hover:not\(:disabled\)\s*\{[\s\S]*?color: #8f4b55/);
  assert.match(css, /\.run-monitor-action-message\s*\{[\s\S]*?border: 0/);
  assert.match(css, /\.run-monitor-action-message\s*\{[\s\S]*?background: #f8fafc/);
  assert.match(css, /\.run-monitor-action-message\s*\{[\s\S]*?font-size: 0\.875rem/);
  assert.match(css, /\.run-monitor-action-message--pending\s*\{[\s\S]*?background: #eff6ff/);
  assert.match(css, /\.run-monitor-action-message--success\s*\{[\s\S]*?background: #fffaf2/);
  assert.match(css, /\.run-monitor-action-message--success\s*\{[\s\S]*?color: #9a6a2f/);
  assert.match(css, /\.run-monitor-action-message--error\s*\{[\s\S]*?color: #c2410c/);
  assert.match(css, /\.run-monitor-action-message--error\s*\{[\s\S]*?background: #fff7ed/);
  assert.match(css, /\.run-monitor-browser__empty-state\s*\{[\s\S]*?text-align: center/);
  assert.match(css, /\.run-monitor-browser__stage--skeleton\s*\{[\s\S]*?animation: runMonitorSkeletonPulse/);
  assert.match(css, /\.run-monitor-skeleton-line\s*\{[\s\S]*?border-radius: 999px/);
  assert.match(css, /@keyframes runMonitorSkeletonPulse/);
  assert.doesNotMatch(css, /\.run-monitor-step--(?:complete|pending)\s*\{[\s\S]*?opacity:/);
  assert.match(css, /\.run-monitor-step--complete \.run-monitor-step__head h3,\s*\n\.run-monitor-step--pending \.run-monitor-step__head h3\s*\{[\s\S]*?color: #64748b/);
  assert.match(css, /\.run-monitor-step--complete \.run-monitor-step__content p,\s*\n\.run-monitor-step--pending \.run-monitor-step__content p\s*\{[\s\S]*?color: #94a3b8/);
  assert.match(css, /@media \(max-width: 1080px\)/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.run-monitor-step\s*\{[\s\S]*?transition: none/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.run-monitor-step:hover\s*\{[\s\S]*?transform: none/);
});
